# filter context
filters: 
  region:
    label: "Region"
    type: string
    request: multi
  city:
    label: "City"
    type: string
    request: multi
  price:
    label: "Price"
    type: float
    request: range

# query context
query:
