category.vehicles.id: 1000
category.vehicles.label: "Vehicles"
category.1000.key: "vehicles"
category.1000.label: "Vehicles"

category.cars.id: 1015
category.cars.label: "Cars"
category.1015.key: "cars"
category.1015.label: "Cars"

category.motorcycles.id: 1040
category.motorcycles.label: "Motorcycles"
category.1040.key: "motorcycles"
category.1040.label: "Motorcycles"

